[package]
name = "brimp-lite-worker"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "lite-worker"
path = "src/main.rs"

[dependencies]
brimp-worker-api = { path = "../worker-api" }
base64 = "0.22"
http = "1"
brimp-network = { path = "../network" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
url = "2"
tokio = { version = "1", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
brimp-runtime = { path = "../runtime" }

[dev-dependencies]
async-trait = "0.1"
libc = "0.2"
