[package]
name = "web-bindings"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64 = "0.22"
blitz-dom = "=0.3.0-beta.1"
browser-dom = { path = "../browser-dom" }
cookie_store = "0.22.1"
encoding_rs = "0.8.35"
http = "1"
jsc = { path = "../jsc" }
network = { path = "../network" }
serde_json = "1"
selectors = "0.39.0"
style = { package = "stylo", version = "0.19.0" }
url = "2"
