[workspace]
members = [
    "crates/jsc-sys",
    "crates/jsc",
    "crates/browser-dom",
    "crates/web-bindings",
    "crates/web-runtime",
    "crates/screenshot",
    "crates/network",
    "crates/cli",
    "benchmark",
    "crates/persona",
    "crates/cdp",
    "bindings/python",
    "bindings/node",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
