[package]
name = "brimp-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "brimp"
path = "src/main.rs"

[dependencies]
http = "1"
glob = "0.3"
brimp-persona = { path = "../persona" }
pico-args = "0.5"
robotstxt = "0.3"
serde_json = "1"
tempfile = "3"
brimp-controller = { path = "../controller" }
brimp-worker-api = { path = "../worker-api" }
url = { version = "2", features = ["serde"] }
