[package]
name = "brimp-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "brimp"
path = "src/main.rs"

[dependencies]
brimp-cdp = { path = "../cdp" }
network = { path = "../network" }
persona = { path = "../persona" }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
web-runtime = { path = "../web-runtime" }
