[package]
name = "screenshot"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyrender = "=0.11.1"
anyrender_vello_cpu = { version = "=0.14.0", default-features = false }
blitz-dom = "=0.3.0-beta.1"
blitz-paint = { version = "=0.3.0-beta.1", default-features = false }
png = "=0.18.1"
